# Generated by Django 3.2.8 on 2021-10-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(blank=True, choices=[('Dhaka ', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Barisal', 'Barisal'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Mymensingh', 'Mymensingh'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet')], max_length=100),
        ),
    ]
